name: Release

on:
  push:
    tags:
      - "v**"

jobs:
  release:
    if: ${{ github.repository == 'ustctug/ustcthesis' }}
    name: Create GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: .github/tl_packages

      - name: Build zip
        run: make zip

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: ustcthesis-*.zip
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
